name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install Web Assembly target
      run: rustup target add wasm32-unknown-unknown
    - name: Install trunk
      run: cargo install trunk
    - name: Build Rust-Yew app
      # Base on `${{ github.event.repository.name }}/`
      # run: trunk build --release --public-path ${{ github.event.repository.name }}
      # Base on `/`
      run: trunk build --release
  # release:
    # xxx
  # deploy:
  #   xxx:
